apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coffeemart
  namespace: coffeemart
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: coffeemart.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coffeemart
                port:
                  number: 80
